name: 'hello_word'
version: '1.0'
config-version: 2

# Define the project paths
model-paths: ["models"]

target-path: "target"
clean-targets: ["target"]

# Specify the profile to use
profile: "hello_world"