# Name of your dbt project.
name: 'hello_word'      
# Version of your dbt project.
version: '1.0'          
# Version of the configuration schema (always 2 for dbt >= 0.17.0)
config-version: 2       

# Directories where your model SQL files are stored. 
# dbt will look in these directories when you run dbt commands.
model-paths: ["models"] 
# Directory where dbt will store the results of running commands like dbt run and dbt test.
target-path: "target" 

# Name of the profile to use for this project. 
# This should match a profile name in your profiles.yml file.
profile: "hello_world" 