# profiles.yml should live in ~/.dbt/ to avoid exposing secrets

# Name of the profile
hello_world:       
  # Target to use from the outputs
  target: dev      
  outputs:
    # Name of the target
    dev:           
      # Type of database you're connecting to
      type: duckdb 
